### ISSUE TITLE
Problemas de diseño con navegadores Chrome y Edge Explorer

### ISSUE THREAD

**Issue by villegascmarco** [pablotz/CryptoDashboard#1]
Parece que los nombres y las décimas están afectando al diseño.

Prueba limitando la longitud de estos elementos.
![image](https://user-images.githubusercontent.com/54155102/119064733-9c6a0880-b9a1-11eb-9ec6-229588392fb6.png)

**Comment by pablotz** [comment]
Solucionado, gracias!
